version: '3'
services:
  backend:
    image: cnunodevs/server-siri:latest
    ports:
      - 14156:14156
    container_name: server-siri
    networks:
      - sirisys

  frontend:
    image: cnunodevs/client-siri:latest
    ports:
      - 4200:4200
    container_name: client-siri
    networks:
      - sirisys

networks:
  sirisys:
